modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
#credits=""
authors="Cake, Kipti"
description='''
Extends fluid dying capability of Bits 'n' Bobs to the entire fluid system, including compatibility for other mods
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"


[[dependencies.${mod_id}]]
    modId="azimuth"
    type="required"
    versionRange="[1.4.6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="bits_n_bobs"
    type="required"
    versionRange="[2.2.4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create_vibrant_vaults"
    type="optional"
    ordering="AFTER"
    side="BOTH"
